program: train.py
project: trajairnet-intent-attention-head
method: bayes
metric:
  name: test_ade_loss
  goal: minimize
parameters:
  # Force single GPU for sweep runs
  force_single_gpu:
    value: true
    
  lr:
    # Sweep over a log-uniform distribution, which is better for learning rates
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01

  scheduler_type:
    values: ['cosine', 'plateau'] # Let wandb test which scheduler is better
  warmup_epochs:
    values: [1, 2, 3] # Add a short warmup period for stability
  
  total_epochs:
    values: [15, 20, 25]
  
  # Intent-specific parameters (default=32, key new feature)
  intent_embed_dim:
    values: [16, 32, 48, 64]
  
  # GAT parameters that interact with intent attention head (defaults: heads=16, hidden=256, dropout=0.05, alpha=0.2)
  gat_heads:
    values: [8, 16, 24, 32]
  graph_hidden:
    values: [128, 256, 384, 512]
  dropout:
    min: 0.02
    max: 0.15
  alpha:
    min: 0.1
    max: 0.3

command:
  - ${env}
  - torchrun
  - --nproc_per_node=1
  - ${program}
  - ${args}

early_terminate:
  type: hyperband
  min_iter: 2
