program: train_sweep.py
method: random
metric:
  name: test_ade_loss
  goal: minimize

parameters:
  # --- Network params to sweep ---
  tcn_channel_size:
    values: [128, 256, 384]
  tcn_layers:
    values: [1, 2, 3]

  gat_heads:
    values: [8, 16, 24]
  graph_hidden:
    values: [128, 256]
  dropout:
    min: 0.05
    max: 0.15
  alpha:
    min: 0.1
    max: 0.3

  # --- Intent embedding params to sweep ---
  intent_embed_dim:
    values: [32, 48, 64]

  # --- Optimization params to sweep ---
  lr:
    values: [0.0005, 0.001, 0.005]

# Optional: you can fix total_epochs in Python defaults
# total_epochs: 20  # leave out to use default
