wandb_version: 1

alpha:
  value: 0.14194171211205422
dropout:
  value: 0.05704278654802564
gat_heads:
  value: 16
graph_hidden:
  value: 128
intent_embed_dim:
  value: 32
lr:
  value: 0.005
tcn_channel_size:
  value: 128
tcn_layers:
  value: 3
