_wandb:
    value:
        cli_version: 0.21.1
        e:
            pnnuqrfo1v80edzbj7d125s72m0pds7y:
                args:
                    - --alpha=0.2492997355959215
                    - --dropout=0.0724196658817799
                    - --gat_heads=16
                    - --graph_hidden=256
                    - --intent_embed_dim=32
                    - --lr=0.001
                    - --tcn_channel_size=384
                    - --tcn_layers=1
                codePath: train_sweep.py
                codePathLocal: train_sweep.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1965440720896"
                        used: "92693471232"
                email: sundharvs@gmail.com
                executable: /home/ssangeetha3/git/ctaf-intent-inference/.pixi/envs/default/bin/python
                git:
                    commit: d7bee4865d9611054d8fed0fdc1de1644577b964
                    remote: git@github.com:sundharvs/trajairnet.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-862c7587-f95e-4e1f-1be0-3160cb489cae
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-49246112-0658-fe8a-9b4c-90699c7b9e2c
                host: MEL07789D.me.gatech.edu
                memory:
                    total: "269349924864"
                os: Linux-6.8.0-65-generic-x86_64-with-glibc2.35
                program: /home/ssangeetha3/git/ctaf-intent-inference/trajairnet/train_sweep.py
                python: CPython 3.12.11
                root: /home/ssangeetha3/git/ctaf-intent-inference/trajairnet
                startedAt: "2025-09-05T22:18:09.137602Z"
                writerId: pnnuqrfo1v80edzbj7d125s72m0pds7y
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 14
                - 16
            "4": 3.12.11
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
alpha:
    value: 0.2492997355959215
cnn_kernels:
    value: 2
cvae_channel_size:
    value: 128
cvae_hidden:
    value: 128
cvae_layers:
    value: 2
dataset_folder:
    value: /storage/home/hcoda1/1/ssangeetha3/p-skousik3-0/ssangeetha3/ctaf-intent-inference/dataset/
dataset_name:
    value: 7daysJune
delim:
    value: ' '
dropout:
    value: 0.0724196658817799
evaluate:
    value: true
gat_heads:
    value: 16
graph_hidden:
    value: 256
input_channels:
    value: 3
intent_embed_dim:
    value: 32
lr:
    value: 0.001
mlp_layer:
    value: 32
model_pth:
    value: /saved_models/
num_context_input_c:
    value: 2
num_context_output_c:
    value: 7
num_intent_classes:
    value: 16
obs:
    value: 11
preds:
    value: 120
preds_step:
    value: 10
save_model:
    value: true
tcn_channel_size:
    value: 384
tcn_kernels:
    value: 4
tcn_layers:
    value: 1
total_epochs:
    value: 20
use_wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: trajairnet-intent-interaction-matrix
