wandb_version: 1

alpha:
  value: 0.25367976758615574
dropout:
  value: 0.06299939061306926
gat_heads:
  value: 8
graph_hidden:
  value: 256
intent_embed_dim:
  value: 48
lr:
  value: 0.005
tcn_channel_size:
  value: 384
tcn_layers:
  value: 1
