wandb_version: 1

alpha:
  value: 0.20151407469322077
dropout:
  value: 0.0854746747042602
gat_heads:
  value: 16
graph_hidden:
  value: 256
intent_embed_dim:
  value: 64
lr:
  value: 0.0005
tcn_channel_size:
  value: 128
tcn_layers:
  value: 1
